import Head from "next/head"
import Navbar from "./Navbar"
import Footer from "./Footer"

export default function Layout({showNavbar = true, title = "MyBlog", children}){
    return(
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {showNavbar && <Navbar/>}
            <main className="main">
                {children}
            </main>
            <Footer/>
        </>
    )
}