import Head from "next/head"
import Navbar from "./Navbar"
import Footer from "./Footer"

export default function Layout({showNavbar = true, title = "MyBlog", children}){
    return(
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>
            </Head>
            {showNavbar && <Navbar/>}
            <main className="main">
                {children}
            </main>
            <Footer/>
        </>
    )
}